# Generated by Django 5.0.7 on 2024-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateint',
            name='profile',
            field=models.ImageField(upload_to='patient/images'),
        ),
    ]
