# Generated by Django 5.0.7 on 2024-08-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='massage',
        ),
    ]
