# Generated by Django 5.0.7 on 2024-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='reviwer',
        ),
    ]
