# Generated by Django 5.0.7 on 2024-08-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_rename_review_review_reviwer'),
        ('patient', '0002_alter_pateint_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('Pendding', 'Pendding'), ('Runing', 'Runing'), ('Complated', 'Complated')], default='Pendding', max_length=50)),
                ('symptoms', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('pateint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.pateint')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime')),
            ],
        ),
    ]
