# Generated by Django 5.0.7 on 2024-08-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pateint',
            new_name='patient',
        ),
    ]
